"""Initial migration.

Revision ID: 1350264f972f
Revises: 
Create Date: 2021-09-20 15:49:58.431832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1350264f972f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aligned_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_source', sa.String(length=200), nullable=False),
    sa.Column('flat_segmentation_source', sa.String(length=200), nullable=True),
    sa.Column('pychunkgraph_segmentation_source', sa.String(length=200), nullable=True),
    sa.Column('pychunkgraph_endpoint', sa.String(length=200), nullable=True),
    sa.Column('annotation_engine_endpoint', sa.String(length=200), nullable=True),
    sa.Column('synapse_segmentation_source', sa.String(length=200), nullable=True),
    sa.Column('pychunkedgraph_viewer_source', sa.String(length=200), nullable=True),
    sa.Column('graphene_source', sa.String(length=200), nullable=True),
    sa.Column('pychunkedgraph_supervoxel_source', sa.String(length=200), nullable=True),
    sa.Column('analysis_database_ip', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissiongroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datastack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aligned_volume_id', sa.Integer(), nullable=True),
    sa.Column('segmentation_source', sa.String(length=200), nullable=True),
    sa.Column('analysis_database', sa.String(length=100), nullable=True),
    sa.Column('viewer_site', sa.String(length=200), nullable=True),
    sa.Column('synapse_table', sa.String(length=100), nullable=True),
    sa.Column('soma_table', sa.String(length=100), nullable=True),
    sa.Column('local_server', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['aligned_volume_id'], ['aligned_volume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tablemapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('permissiongroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permissiongroup_id'], ['permissiongroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tablemapping')
    op.drop_table('datastack')
    op.drop_table('permissiongroup')
    op.drop_table('dataset')
    op.drop_table('aligned_volume')
    # ### end Alembic commands ###
