"""adding image source model

Revision ID: 72ab15bad6f8
Revises: a9871e1e247e
Create Date: 2023-06-05 13:26:09.728403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ab15bad6f8'
down_revision = 'a9871e1e247e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ngl_layer_name', sa.String(length=100), nullable=True),
    sa.Column('image_source', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('aligned_volume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aligned_volume_id'], ['aligned_volume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_source')
    # ### end Alembic commands ###
