"""Add voxel resolution

Revision ID: 892bdde0c2f4
Revises: 1350264f972f
Create Date: 2021-09-20 16:02:49.313308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892bdde0c2f4'
down_revision = '1350264f972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datastack', sa.Column('viewer_resolution_x', sa.Float(), nullable=True))
    op.add_column('datastack', sa.Column('viewer_resolution_y', sa.Float(), nullable=True))
    op.add_column('datastack', sa.Column('viewer_resolution_z', sa.Float(), nullable=True))
    op.create_unique_constraint("permissiongroup_uniq", 'permissiongroup', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("permissiongroup_uniq", 'permissiongroup', type_='unique')
    op.drop_column('datastack', 'viewer_resolution_z')
    op.drop_column('datastack', 'viewer_resolution_y')
    op.drop_column('datastack', 'viewer_resolution_x')
    # ### end Alembic commands ###
