"""adding big integer base link id

Revision ID: 9e8b9d192ad8
Revises: 892bdde0c2f4
Create Date: 2021-09-29 16:48:17.226779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8b9d192ad8'
down_revision = '892bdde0c2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datastack', sa.Column('base_link_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datastack', 'base_link_id')
    # ### end Alembic commands ###
