"""adding proofreading tables

Revision ID: a9871e1e247e
Revises: 9e8b9d192ad8
Create Date: 2023-03-27 12:26:16.770416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9871e1e247e"
down_revision = "9e8b9d192ad8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datastack",
        sa.Column("proofreading_status_table", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "datastack",
        sa.Column("cell_identification_table", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "datastack",
        sa.Column("proofreading_review_table", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datastack", "proofreading_review_table")
    op.drop_column("datastack", "cell_identification_table")
    op.drop_column("datastack", "proofreading_status_table")
    # ### end Alembic commands ###
