"""adding display names to aligned volume and datastacks

Revision ID: b0b51fd07bfa
Revises: 72ab15bad6f8
Create Date: 2023-06-05 17:03:38.160408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b51fd07bfa'
down_revision = '72ab15bad6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aligned_volume', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('datastack', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datastack', 'display_name')
    op.drop_column('aligned_volume', 'display_name')
    # ### end Alembic commands ###
