"""adding skeleton source

Revision ID: df5b03b51b24
Revises: 6c4b42b01045
Create Date: 2024-07-15 08:12:00.399951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5b03b51b24'
down_revision = '6c4b42b01045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datastack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skeleton_source', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datastack', schema=None) as batch_op:
        batch_op.drop_column('skeleton_source')

    # ### end Alembic commands ###
