"""add catalog_url to datastack

Revision ID: e07b444cb63b
Revises: a9871e1e247e
Create Date: 2026-05-12 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e07b444cb63b"
down_revision = "a9871e1e247e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datastack",
        sa.Column("catalog_url", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datastack", "catalog_url")
    # ### end Alembic commands ###
